version: '2'

services:
  website:
    build: client
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "spectral.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '9000:8000'
  grpc_server:
    build: grpc_server
    command: python spectral/app.py
    environment:
      PYTHONUNBUFFERED: 'true'
