import subprocess

import click


@click.command()
@click.option('--skip-init/--no-skip-init', default=True,
              help='Skip __init__.py files?')
@click.option('--skip-autogen/--no-skip-autogen', default=True,
              help='Skip gRPC autogenerated files?')
@click.argument('path', default='spectral')
def cli(skip_init, skip_autogen, path):
    """
    Run flake8 to analyze your code base.

    :param skip_init: Skip checking __init__.py files
    :param path: Test coverage path
    :return: Subprocess call result
    """
    flake8_flag_exclude = ''

    if skip_init:
        flake8_flag_exclude = ' --exclude __init__.py'

    # Skips autogenerated gRPC files since they have a lot of warnings
    if skip_autogen:
        flake8_flag_exclude += ',gen_grpc'

    cmd = 'flake8 {0}{1}'.format(path, flake8_flag_exclude)
    return subprocess.call(cmd, shell=True)
